server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:5002/cardsdb
#    driver-class-name: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
  #        dialect: org.hibernate.dialect.H2Dialect  # Uncomment and use if H2 database is needed
  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "cards"
    description: "AnhTuan Card Application"
    version: "1.0.0"
