server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:5001/loansdb
    #    driver-class-name:
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
  #        dialect: org.hibernate.dialect.H2Dialect  # Uncomment and use if H2 database is needed
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    fetch-registry: true
    register-with-eureka: true
info:
  app:
    name: "loans"
    description: "AnhTuan Loan Application"
    version: "1.0.0"
